### ISSUE TITLE
Create option to export to a 1.15 model class

### ISSUE THREAD

**Issue by visceralfield** [UpcraftLP/FabricEntityModelMapper#1]
Things are almost the same in 1.15, adding cuboids has just switched to this:
`bb_main.addCuboid(name, x, y, z, sizeX, sizeY, sizeZ, extra, u, v)`

I'd submit a PR if I understood this remapping stuff, but the info's all the same just in a different order. Any chance we could see this?

**Comment by UpcraftLP** [comment]
Sorry, the project is rather broken at the moment, and I don't really plan on fixing it.
This was just a temporary thing so I could get a few models fixed, it was never intended to be the go-to solution for entity models.
